services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_SERVER_DOMAIN: ${VITE_SERVER_DOMAIN:-http://localhost:8080}
    ports:
      - "${PORT:-80}:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev