name: deploy-front

on:
  push:
    branches:
      - 13269

jobs:
  connect_to_server:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH directory
      run: mkdir -p ~/.ssh

    - name: Install ssh keys
      run: |
        echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
        chmod 600 ~/.ssh/front_rsa

    - name: Add host to known_hosts
      run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    # - name: Debug SSH keys
    #   run: |
    #     ls -la ~/.ssh
    #     echo "known_hosts:"
    #     cat ~/.ssh/known_hosts

    - name: Connect and pull
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
          echo "----- Connected to server -----"
          
          cd /home/${{ secrets.SSH_USER }} ${{ secrets.FRONT_WORK_DIR }} 
          echo "Now in project dir:"
          pwd

          git checkout origin/checkactions13269
          git pull

          exit
        '
# if [ ! -f env.front_vm ]; then
#   git clone git@github.com:os-nsu/ostest-plan.git
#   mv ostest-plan/env.front_vm .
#   rm -rf ostest-plan
# fi
    - name: Cleanup
      run: rm -rf ~/.ssh
    
  # build:
  #   runs-on: ubuntu-latest
  #   needs: connect_to_server

  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3

  #     - name: Deploy to our remote server
  #       run: |
  #         ssh -i ~/.ssh/front_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
  #           cd ${{ secrets.FRONT_WORK_DIR }}
  #           git pull 
            
  #           docker-compose down
  #           docker compose --env-file env.front_vm up --build
          
  #         EOF | tee deployment_log.txt

  #     - name: See logs
  #       uses: actions/upload-artifact@v4
  #       with:
  #         path: deployment_log.txt
