name: deploy-front

on:
  push:
    branches:
      - feature/14348/fixes-deploy

jobs:
  connect_to_server:
    name: run pull
    runs-on: ubuntu-24.04

    steps:
    - name: Setup SSH directory
      run: mkdir -p ~/.ssh

    - name: Install ssh keys
      run: |
        echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
        chmod 600 ~/.ssh/front_rsa

    - name: Add host to known_hosts
      run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Add osplan SSH Key
      run: |
        echo "${{ secrets.OSPLAN_SSH_PRIVATE_KEY }}" > ~/.ssh/osplan_rsa
        chmod 600 ~/.ssh/osplan_rsa

    - name: Connect and pull
      run: |
        ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
        set -e

        echo "----- Connected to server -----"

          cd ${{ secrets.FRONT_WORK_DIR }}
          echo "Now in project dir:"
          pwd
          ls -la

          sudo chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} *

          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/osplan_rsa

          git reset --hard HEAD
          git clean -fd
          git fetch --all
          git checkout master
          git pull origin master

          if [ ! -f env.front_vm ]; then
            echo "env.front_vm not found. Cloning repository to fetch it..."

            if [ -d "ostest-plan" ]; then
              echo "Directory ostest-plan already exists. Removing it..."
              rm -rf ostest-plan
            fi

            if ! git clone https://github.com/os-nsu/ostest-plan.git; then
              echo "Failed to clone repository"
              exit 1
            fi

            cd ostest-plan
            git checkout 14348
            git pull origin 14348
            cd ..

            mv ostest-plan/env.front_vm .
            rm -rf ostest-plan

            echo "Moved env file"
            else
            echo "env.front_vm already exists"
            fi

          exit
        '

  build:
    runs-on: ubuntu-24.04
    needs: connect_to_server

    steps:
      - name: Setup SSH directory
        run: mkdir -p ~/.ssh

      - name: Install ssh keys
        run: |
          echo "${{ secrets.FRONT_SSH_PRIVATE_KEY }}" > ~/.ssh/front_rsa
          chmod 600 ~/.ssh/front_rsa

      - name: Add host to known_hosts
        run: ssh-keyscan -H -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to our remote server
        run: |
          set -e
          ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/front_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF | tee deployment_log.txt
          cd ${{ secrets.FRONT_WORK_DIR }}
          git pull
          docker-compose down
          docker compose --env-file env.front_vm up --build -d
           
          docker logs $(docker ps -q --filter "ancestor=ostest-front-frontend")
          EOF

      - name: See logs
        uses: actions/upload-artifact@v4
        with:
          path: deployment_log.txt